### ISSUE TITLE
Installation Successful, however dashboard is not connecting !!

### ISSUE THREAD

**Issue by ragupathys** [aptira/guts#66]
Hi,

I have followed the automated way of devstack installation on both RHEL 7.2 & CentOS 7, the installation completed successfully however not able to get the dashboard.
I tried to isolate the problem & found without guts injection, able to successfully deploy openstack and login after iptables -F.
With GUTS installation, explored a little & ended up in capturing the below error message under /var/log/httpd/horizon_error.log
Can you please help me to fix this & proceed further. Thanks.,

---------------------------------------------------------------------------------------------------
2016-09-22 08:44:58.270718 mod_wsgi (pid=13338): Exception occurred processing WSGI script '/opt/stack/horizon/openstack_dashboard/wsgi/django.wsgi'.
2016-09-22 08:44:58.270819 Traceback (most recent call last):
2016-09-22 08:44:58.270845   File "/usr/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 170, in __call__
2016-09-22 08:44:58.270884     self.load_middleware()
2016-09-22 08:44:58.270896   File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 52, in load_middleware
2016-09-22 08:44:58.270915     mw_instance = mw_class()
2016-09-22 08:44:58.270925   File "/usr/lib/python2.7/site-packages/django/middleware/locale.py", line 24, in __init__
2016-09-22 08:44:58.270944     for url_pattern in get_resolver(None).url_patterns:
2016-09-22 08:44:58.270954   File "/usr/lib/python2.7/site-packages/django/core/urlresolvers.py", line 401, in url_patterns
2016-09-22 08:44:58.270971     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
2016-09-22 08:44:58.270979   File "/usr/lib/python2.7/site-packages/django/core/urlresolvers.py", line 395, in urlconf_module
2016-09-22 08:44:58.270993     self._urlconf_module = import_module(self.urlconf_name)
2016-09-22 08:44:58.271002   File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
2016-09-22 08:44:58.271018     __import__(name)
2016-09-22 08:44:58.271029   File "/opt/stack/horizon/openstack_dashboard/wsgi/../../openstack_dashboard/urls.py", line 38, in <module>
2016-09-22 08:44:58.271048     url(r'', include(horizon.urls)),
2016-09-22 08:44:58.271057   File "/usr/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 34, in include
2016-09-22 08:44:58.271145     patterns = getattr(urlconf_module, 'urlpatterns', urlconf_module)
2016-09-22 08:44:58.271173   File "/usr/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
2016-09-22 08:44:58.271316     self._setup()
2016-09-22 08:44:58.271340   File "/usr/lib/python2.7/site-packages/django/utils/functional.py", line 376, in _setup
2016-09-22 08:44:58.271361     self._wrapped = self._setupfunc()
2016-09-22 08:44:58.271370   File "/opt/stack/horizon/openstack_dashboard/wsgi/../../horizon/base.py", line 828, in url_patterns
2016-09-22 08:44:58.271669     return self._urls()[0]
2016-09-22 08:44:58.271697   File "/opt/stack/horizon/openstack_dashboard/wsgi/../../horizon/base.py", line 862, in _urls
2016-09-22 08:44:58.271719     include(dash._decorated_urls)))
2016-09-22 08:44:58.271731   File "/opt/stack/horizon/openstack_dashboard/wsgi/../../horizon/base.py", line 543, in _decorated_urls
2016-09-22 08:44:58.271747     % self.default_panel)
2016-09-22 08:44:58.271769 NotRegistered: The default panel "None" is not registered.
---------------------------------------------------------------------------------------------------

**Comment by rajalokan** [comment]
Hello ragupathys, there has been some change in dashboard panels but not updated in `devstack` setup. This might be reason it is breaking. 

Here are the steps I would follow to get it working.
* Make sure `guts-dashboard` is at latest master.
* As you said without `guts-dashboard` injection dashboard is working. This is great.
* Now we need to inject `guts-dashboard` configurations. We need to go to `/opt/stack/horizon/openstack_dashboard/local/enabled` and inject four `guts-dashboard` config files by making links. 
* These files are present in `guts-dashboard` code at `/opt/stack/guts-dashboard/gutsdashboard/local` namely
_5010_guts_services.py
_5020_guts_resources.py
_5030_guts_migrations.py
_50_guts.py_50_guts.pyc

Please try this and let us know if issue remains.

**Comment by balagopalraj** [comment]
Fix Committed.
id : 29d924a9922aa90e38a1324473892aea35473184

**Comment by ragupathys** [comment]
Hi rajalokan & balagopalraj,

I have tried reinstallation & found it is failing in the following ;

++lib/neutron_plugins/services/l3:_neutron_configure_router_v4:367  ip addr show dev br-ex
++lib/neutron_plugins/services/l3:_neutron_configure_router_v4:367  grep -c 172.24.4.1
+lib/neutron_plugins/services/l3:_neutron_configure_router_v4:367  [[ 0 == 0 ]]
+lib/neutron_plugins/services/l3:_neutron_configure_router_v4:367  [[ True == \F\a\l\s\e ]]
+lib/neutron_plugins/services/l3:_neutron_configure_router_v4:367  [[ False == \T\r\u\e ]]
+lib/neutron_plugins/services/l3:_neutron_configure_router_v4:367  [[ True == \T\r\u\e ]]
+lib/neutron_plugins/services/l3:_neutron_configure_router_v4:368  sudo ip addr add 172.24.4.1/24 dev br-ex
+lib/neutron_plugins/services/l3:_neutron_configure_router_v4:369  sudo ip link set br-ex up
++lib/neutron_plugins/services/l3:_neutron_configure_router_v4:371  tr '\n' ' '
++lib/neutron_plugins/services/l3:_neutron_configure_router_v4:371  neutron --os-cloud devstack-admin --os-region RegionOne port-list -c fixed_ips -c device_owner
++lib/neutron_plugins/services/l3:_neutron_configure_router_v4:371  grep router_gateway
++lib/neutron_plugins/services/l3:_neutron_configure_router_v4:371  cut -f3 '-d"'
++lib/neutron_plugins/services/l3:_neutron_configure_router_v4:371  awk -Fip_address '{ print $2 }'
+lib/neutron_plugins/services/l3:_neutron_configure_router_v4:371  ROUTER_GW_IP='172.24.4.8 '
+lib/neutron_plugins/services/l3:_neutron_configure_router_v4:372  die_if_not_set 372 ROUTER_GW_IP 'Failure retrieving ROUTER_GW_IP'
+functions-common:die_if_not_set:204       local exitcode=0
+functions-common:die_if_not_set:205       local xtrace
++functions-common:die_if_not_set:206       grep xtrace
++functions-common:die_if_not_set:206       set +o
+functions-common:die_if_not_set:206       xtrace='set -o xtrace'
+functions-common:die_if_not_set:207       set +o xtrace
+lib/neutron_plugins/services/l3:_neutron_configure_router_v4:373  local replace_range=10.0.0.0/8
+lib/neutron_plugins/services/l3:_neutron_configure_router_v4:374  [[ -z a1604655-3fb5-4ef1-8a85-2b54942f8f35 ]]
+lib/neutron_plugins/services/l3:_neutron_configure_router_v4:377  sudo ip route replace 10.0.0.0/8 via 172.24.4.8

Can you update on the issue please. Thanks.,
